FROM openjdk:8
EXPOSE 8080
copy nasabah-0.0.1-SNAPSHOT.jar nasabah.jar
CMD ["java","-jar","/nasabah.jar"]

From openjdk:8
copy ./target/employee-jdbc-0.0.1-SNAPSHOT.jar employee-jdbc-0.0.1-SNAPSHOT.jar
CMD ["java","-jar","employee-jdbc-0.0.1-SNAPSHOT.jar"]